### ISSUE TITLE
POWERLEVEL9K_MODE is defined twice

### ISSUE THREAD

**Issue by williambelle** [obieler/dotfiles#1]
See:

https://github.com/obieler/dotfiles/blob/daf3addfc3e1c7d58f074c1fd1b1578ef0df33a9/.powerlevel9k#L3
https://github.com/obieler/dotfiles/blob/daf3addfc3e1c7d58f074c1fd1b1578ef0df33a9/.powerlevel9k#L11

**Comment by obieler** [comment]
@williambelle Thanks dude! :+1:
